// web_system_cafe/src/pages/auth/LoginPage.vue
<script setup>
import { reactive } from 'vue';
import { request } from '../../store/Configstore';
import { setAcccessToken, setProfile } from '../../store/profile';
import { useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
const router = useRouter();


const login = reactive({
    email: '',
    password: ''
});



const handleLogin = async () => {
    try {
        const param = {
            email: login.email,
            password: login.password,
        };
        const res = await request('login', 'post', param);
        console.log(res);
        if (res && !res.error) {
            setAcccessToken(res.token);
            setProfile(JSON.stringify(res.user));
            message.success(res.message)

            router.push('/');
        } else {
            message.warning(res.message)
        }
    } catch (error) {
        message.error(error)
    }
};


</script>

<template>
    <div class="p-5">
        <!-- Login Form -->
        <form @submit.prevent="handleLogin">
            <div class="mb-4">
                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                <input type="email" id="email"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                    v-model="login.email" required />
            </div>
            <div class="mb-4">
                <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                <input type="password" id="password"
                    class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
                    v-model="login.password" required />
            </div>
            <button type="submit" class="w-full py-2 px-4 bg-blue-600 text-white rounded-md hover:bg-blue-700">
                Login
            </button>
        </form>
        <div class="mt-4 text-center">
            <p class="text-sm text-gray-600">
                Don't have an account?
                <router-link to="/register" class="text-blue-500 hover:underline">Sign Up</router-link>
            </p>
        </div>
    </div>
</template>

// web_system_cafe/src/pages/auth/LoginPage.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { message, Spin, Form, Input, Button } from "antd";
import { request } from "../../store/Configstore";
import { setAcccessToken, setProfile } from "../../store/profile";

const LoginPage = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);

  const handleLogin = async (values) => {
    try {
      setLoading(true);
      const param = {
        email: values.email,
        password: values.password,
      };
      const res = await request("login", "post", param);
      console.log(res);
      if (res && !res.error) {
        setAcccessToken(res.token);
        setProfile(JSON.stringify(res.user));
        message.success(res.message);
        navigate("/");
      }
    } catch (error) {
      message.error(error.message || "ការចូលប្រើបានបរាជ័យ។");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      {loading ? (
        <Spin spinning={loading}>
          <div className="p-5">
            <Form
              name="login"
              onFinish={handleLogin}
              initialValues={{ email: "", password: "" }}
              layout="vertical"
            >
              <Form.Item
                className="font-battambang"
                label="អ៊ីម៉ែល"
                name="email"
                rules={[
                  { required: true, message: "សូមបញ្ចូលអ៊ីម៉ែលរបស់អ្នក!" },
                  { type: "email", message: "សូមបញ្ចូលអ៊ីម៉ែលដែលត្រឹមត្រូវ!" },
                ]}
              >
                <Input
                  type="email"
                  placeholder="បញ្ចូលអ៊ីម៉ែលរបស់អ្នក"
                  className="font-battambang"
                />
              </Form.Item>

              <Form.Item
                label="ពាក្យសម្ងាត់"
                name="password"
                className="font-battambang"
                rules={[
                  { required: true, message: "សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក!" },
                ]}
              >
                <Input.Password
                  placeholder="បញ្ចូលពាក្យសម្ងាត់របស់អ្នក"
                  className="font-battambang"
                />
              </Form.Item>

              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  block
                  className="font-battambang"
                  loading={loading}
                >
                  ចូលប្រើ
                </Button>
              </Form.Item>
            </Form>
            <div className="mt-4 text-center">
              <p className="text-sm text-gray-600 font-battambang">
                មិនមានគណនីទេ?
                <a
                  href="/register"
                  className="text-blue-500 hover:underline font-battambang"
                >
                  ចុះឈ្មោះ
                </a>
              </p>
            </div>
          </div>
        </Spin>
      ) : (
        <div className="p-5">
          <Form
            name="login"
            onFinish={handleLogin}
            initialValues={{ email: "", password: "" }}
            layout="vertical"
          >
            <Form.Item
              label="អ៊ីម៉ែល"
              name="email"
              className="font-battambang"
              rules={[
                { required: true, message: "សូមបញ្ចូលអ៊ីម៉ែលរបស់អ្នក!" },
                { type: "email", message: "សូមបញ្ចូលអ៊ីម៉ែលដែលត្រឹមត្រូវ!" },
              ]}
            >
              <Input
                type="email"
                placeholder="បញ្ចូលអ៊ីម៉ែលរបស់អ្នក"
                className="font-battambang"
              />
            </Form.Item>

            <Form.Item
              label="ពាក្យសម្ងាត់"
              name="password"
              className="font-battambang"
              rules={[
                { required: true, message: "សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក!" },
              ]}
            >
              <Input.Password
                placeholder="បញ្ចូលពាក្យសម្ងាត់របស់អ្នក"
                className="font-battambang"
              />
            </Form.Item>

            <Form.Item>
              <Button
                type="primary"
                className="font-battambang"
                htmlType="submit"
                block
                loading={loading}
              >
                ចូលប្រើ
              </Button>
            </Form.Item>
          </Form>
          <div className="mt-4 text-center">
            <p className="text-sm text-gray-600 font-battambang">
              មិនមានគណនីទេ?
              <a
                href="/register"
                className="text-blue-500 hover:underline font-battambang"
              >
                ចុះឈ្មោះ
              </a>
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default LoginPage;
